'use strict';
const crypto=require('node:crypto');
const RULES='survival-expedition-0.1.9';const PREFIX='/api/unity/survival/v1';
class ContractError extends Error{constructor(status,code){super(code);this.status=status;this.code=code;}}
function check(ok,status,code){if(!ok)throw new ContractError(status,code);}
function uuid(value){return typeof value==='string'&&/^[a-zA-Z0-9_-]{16,80}$/.test(value);}
class SurvivalService{
 constructor(store,questions,clock=Date.now){this.store=store;this.bank=questions;this.now=clock;this.digest=crypto.createHash('sha256').update(JSON.stringify(questions)).digest('hex');}
 public(run){const q=run.question;return{expeditionId:run.id,rulesVersion:RULES,questionBankVersion:this.digest,stateRevision:run.revision,state:run.state,lives:run.lives,sectorReached:run.sector,sectorsCleared:run.cleared,questionInSector:run.inSector,questionSequence:run.sequence,route:run.route,extraSeconds:run.extra,focusStacks:run.focus,questionsAnswered:run.answers.length,correct:run.correct,wrong:run.wrong,timeouts:run.timeouts,provisionalScore:run.score,serverTime:this.now(),expiresAt:run.expiresAt,question:run.state==='Question'?{instanceId:q.instance,sequence:run.sequence,prompt:q.prompt,category:q.category,difficulty:q.difficulty,options:q.options,issuedAt:q.issuedAt,deadlineAt:q.deadline}:null,resolution:run.resolution||null,result:run.result||null};}
 present(run){const target=Math.max(run.highestDifficulty,Math.min(3,Math.ceil(run.sector/2)+(run.route==='pressure'?1:0)));run.highestDifficulty=target;const remaining=this.bank.filter(q=>!run.used.includes(String(q.id)));check(remaining.length>0,503,'BANK_EXHAUSTED');const gap=Math.min(...remaining.map(q=>Math.abs(q.difficulty-target)));const eligible=remaining.filter(q=>Math.abs(q.difficulty-target)===gap);const q=eligible[crypto.randomInt(eligible.length)];run.used.push(String(q.id));const order=[0,1,2,3];for(let i=3;i>0;i--){const j=crypto.randomInt(i+1);[order[i],order[j]]=[order[j],order[i]];}const options=order.map(i=>({optionId:crypto.randomUUID(),text:q.answers[i]}));const issuedAt=this.now();const limitMs=(16-run.sector-(run.route==='pressure'?3:0)+run.extra)*1000;run.sequence++;run.question={sourceId:String(q.id),instance:crypto.randomUUID(),prompt:q.question,category:q.category,difficulty:q.difficulty,options,correctOption:options[order.indexOf(q.correct)].optionId,issuedAt,deadline:issuedAt+limitMs,limitMs};run.state='Question';}
 finish(doc,run,outcome){run.state=outcome==='abandoned'?'Abandoned':'Completed';const previous=doc.records[RULES]?.score||0;const eligible=outcome==='victory'||outcome==='defeat';if(eligible&&run.score>previous)doc.records[RULES]={score:run.score,expeditionId:run.id,sectorReached:run.sector,verifiedAt:this.now()};run.result={expeditionId:run.id,rulesVersion:RULES,status:'verified',outcome,sectorReached:run.sector,sectorsCleared:run.cleared,questionsAnswered:run.answers.length,correct:run.correct,wrong:run.wrong,timeouts:run.timeouts,livesRemaining:run.lives,validatedScore:run.score,previousPersonalBest:previous,personalBest:doc.records[RULES]?.score||0,newPersonalBest:eligible&&run.score>previous,verifiedAt:this.now(),rewards:{status:'disabled',policyVersion:null,grantId:null,items:[]}};}
 resolve(doc,run,option,timedOut){const q=run.question;const correct=!timedOut&&option===q.correctOption;const remaining=Math.max(0,q.deadline-this.now())/1000;const base=100+20*q.difficulty+4*Math.floor(remaining);const multiplier=(run.route==='pressure'?1.25:1)*(1+.1*run.focus);const score=correct?Math.floor(base*multiplier):0;run.score+=score;if(correct)run.correct++;else{run.wrong++;run.lives--;}if(timedOut)run.timeouts++;run.answers.push({questionId:q.sourceId,instanceId:q.instance,sequence:run.sequence,sector:run.sector,difficulty:q.difficulty,optionId:option,elapsedMs:Math.min(q.limitMs,Math.max(0,this.now()-q.issuedAt)),correct,timedOut,scoreAwarded:score});run.resolution={correct,timedOut,correctOptionId:q.correctOption,selectedOptionId:option||'',scoreAwarded:score};run.state='Feedback';if(run.lives===0)this.finish(doc,run,'defeat');}
 reconcile(doc,run){if(run.result)return;if(this.now()>=run.expiresAt){this.finish(doc,run,'expired');run.revision++;return;}if(run.state==='Question'&&this.now()>=run.question.deadline){this.resolve(doc,run,null,true);run.revision++;}}
 async start(player,b){check(uuid(b.clientRequestId),400,'INVALID_START_ID');return this.store.transaction(player,doc=>{const old=doc.starts[b.clientRequestId];if(old){check(doc.runs[old],410,'EXPEDITION_EXPIRED');this.reconcile(doc,doc.runs[old]);return {ok:true,state:this.public(doc.runs[old])};}for(const run of Object.values(doc.runs)){this.reconcile(doc,run);check(!!run.result,409,'EXPEDITION_ALREADY_ACTIVE');}check(Object.keys(doc.runs).length<100,429,'EXPEDITION_RETENTION_LIMIT');const run={id:crypto.randomUUID(),revision:1,state:'Created',lives:3,sector:1,inSector:1,cleared:0,sequence:0,route:'balanced',extra:0,focus:0,highestDifficulty:1,score:0,correct:0,wrong:0,timeouts:0,used:[],answers:[],routes:[],upgrades:[],actions:{},expiresAt:this.now()+30*60*1000};this.present(run);doc.runs[run.id]=run;doc.starts[b.clientRequestId]=run.id;return{ok:true,state:this.public(run)};});}
 async state(player,id){return this.store.transaction(player,doc=>{const run=doc.runs[id];check(run,404,'EXPEDITION_NOT_FOUND');this.reconcile(doc,run);return{ok:true,state:this.public(run)};});}
 async records(player){return this.store.transaction(player,doc=>({ok:true,record:doc.records[RULES]||{score:0},rulesVersion:RULES}));}
 async action(player,id,b){check(uuid(b.actionId)&&Number.isSafeInteger(b.expectedRevision),400,'INVALID_ACTION');const allowed={answer:['questionInstanceId','optionId'],continue:[],choose_route:['routeId'],choose_upgrade:['upgradeId'],abandon:[],timeout_hint:[]};check(Object.hasOwn(allowed,b.type),400,'INVALID_ACTION_TYPE');const fields=['token','actionId','expectedRevision','type',...allowed[b.type]];check(Object.keys(b).every(k=>fields.includes(k)),400,'UNEXPECTED_FIELD');const fingerprint=crypto.createHash('sha256').update(JSON.stringify([b.expectedRevision,b.type,...allowed[b.type].map(k=>b[k])])).digest('hex');return this.store.transaction(player,doc=>{const run=doc.runs[id];check(run,404,'EXPEDITION_NOT_FOUND');const replay=run.actions[b.actionId];if(replay){check(replay.fingerprint===fingerprint,409,'IDEMPOTENCY_CONFLICT');this.reconcile(doc,run);return{ok:true,duplicate:true,ackActionId:b.actionId,state:this.public(run)};}check(b.expectedRevision===run.revision,409,'STALE_REVISION');const revision=run.revision;this.reconcile(doc,run);if(run.revision!==revision){run.actions[b.actionId]={fingerprint};return{ok:true,duplicate:false,ackActionId:b.actionId,state:this.public(run)};}check(!run.result,409,'EXPEDITION_TERMINAL');check(Object.keys(run.actions).length<100,429,'ACTION_LIMIT');
 switch(b.type){
 case 'answer':check(run.state==='Question',409,'INVALID_STATE');check(b.questionInstanceId===run.question.instance,409,'QUESTION_MISMATCH');check(run.question.options.some(o=>o.optionId===b.optionId),400,'OPTION_MISMATCH');this.resolve(doc,run,b.optionId,false);break;
 case 'continue':check(run.state==='Feedback',409,'INVALID_STATE');if(run.inSector<3){run.inSector++;this.present(run);}else{run.cleared=run.sector;if(run.sector===5)this.finish(doc,run,'victory');else run.state=[2,4].includes(run.sector)?'Sanctuary':'RouteChoice';}break;
 case 'choose_route':check(run.state==='RouteChoice',409,'INVALID_STATE');check(['balanced','pressure'].includes(b.routeId),400,'INVALID_ROUTE');run.routes.push({fromSector:run.sector,toSector:run.sector+1,routeId:b.routeId});run.route=b.routeId;run.sector++;run.inSector=1;this.present(run);break;
 case 'choose_upgrade':check(run.state==='Sanctuary',409,'INVALID_STATE');check(['recover_life','extra_time','focus'].includes(b.upgradeId),400,'INVALID_UPGRADE');if(b.upgradeId==='recover_life'){check(run.lives<3,409,'LIVES_FULL');run.lives++;}else if(b.upgradeId==='extra_time')run.extra+=2;else run.focus++;run.upgrades.push({sector:run.sector,upgradeId:b.upgradeId});run.state='RouteChoice';break;
 case 'abandon':this.finish(doc,run,'abandoned');break;
 case 'timeout_hint':throw new ContractError(409,'DEADLINE_NOT_EXPIRED');
 }
 run.revision++;run.actions[b.actionId]={fingerprint};return{ok:true,duplicate:false,ackActionId:b.actionId,state:this.public(run)};});}
}
function createRouter({getStore,questions,authenticate,readBody,json}){let service;return async(req,res,p)=>{if(!p.startsWith(PREFIX+'/'))return false;try{check(req.method==='POST',405,'METHOD_NOT_ALLOWED');const b=await readBody(req);check(b&&typeof b==='object'&&!Array.isArray(b),400,'INVALID_BODY');const session=authenticate(String(b.token||''));check(session,401,'UNAUTHORIZED');service??=new SurvivalService(getStore(),questions);let reply;if(p===PREFIX+'/expeditions/start'){check(Object.keys(b).every(k=>['token','clientRequestId'].includes(k)),400,'UNEXPECTED_FIELD');reply=await service.start(session.playerId,b);}else if(p===PREFIX+'/records/me')reply=await service.records(session.playerId);else{const match=p.match(/^\/api\/unity\/survival\/v1\/expeditions\/([0-9a-f-]{36})\/(actions|state|result)$/);check(match,404,'ROUTE_NOT_FOUND');reply=match[2]==='actions'?await service.action(session.playerId,match[1],b):await service.state(session.playerId,match[1]);}json(res,200,reply);}catch(e){const status=e.status||503;json(res,status,{ok:false,error:status>=500?'Servicio de expedición no disponible':e.code,code:e.code||'SURVIVAL_UNAVAILABLE',retryable:status>=500||status===429});}return true;};}
module.exports={SurvivalService,createRouter,RULES,ContractError};